
#define MICBASE				'MIC0'


#define MIC_HELLO					(MICBASE+0)

#define MIC_GET_CURRENT_LINE		(MICBASE+1)
#define MIC_GET_CURRENT_COL			(MICBASE+2)
#define MIC_GET_CURRENT_FILE		(MICBASE+3)
#define MIC_GET_LINE_AS_STRING		(MICBASE+4)
#define MIC_MOVE_CURSOR				(MICBASE+5)

#define MIC_LIST_OPEN_FILES			(MICBASE+6)
#define MIC_OPEN_FILE				(MICBASE+7)
#define MIC_MAKE_LINE_VISIBLE		(MICBASE+8)

#define MIC_LAST					(MICBASE+8)
