COMPILE=g++ -g -c %SRCFILE% -Wno-narrowing -Wno-write-strings -Wno-multichar -Wno-unused-result -Wunused-variable -o %MODULE%.%OBJ_EXT%
LPREFIX=g++
LSUFFIX=-o %OUTPUT% -lbe -ltracker
OBJ_EXT=o
OUTPUT=sisong
NO_STATERR=1
#BUILDSTAMP=buildstamp.cpp

>>
MainWindow.cpp
EditArea.cpp
EditPane.cpp
main.cpp
edit.cpp
edit_files.cpp
edit_keys.cpp
edit_cursor.cpp
UpdateLine.cpp
selection.cpp
edit_actions.cpp
line.cpp
lexer.cpp
redraw.cpp
Templates.cpp
InputBox.cpp
NewProject.cpp
projects.cpp
layout.cpp
PopupPane.cpp
CompilePane.cpp
SearchResults.cpp
BuildHelpPane.cpp
menu.cpp
draw_cursor.cpp
LNPanel.cpp
spacer.cpp
cmdseq.cpp
FindBox.cpp
DocPoint.cpp
edit_mouse.cpp
undo.cpp
bmatch.cpp
tabs.cpp
misc.cpp
clipboard.cpp
colors.cpp
config.cpp
ViewTimer.cpp
FontDrawer.cpp
SubWindow.cpp
ColoredStringItem.cpp
OffscreenBuffer.cpp
FunctionList.cpp
AutoSaver.cpp
testview.cpp
CList.cpp
MessageView.cpp
NotifyUpdate.cpp
stats.cpp
Prefs/Prefs.cpp
Prefs/AboutPreflet.cpp
Prefs/CheckboxPreflet.cpp
Prefs/ColorsPreflet.cpp
Prefs/ColorItem.cpp
Prefs/ColorView.cpp
Prefs/ShortcutsPreflet.cpp
Prefs/StatsPreflet.cpp
FileView/IconCache.cpp
FileView/QuickSearch.cpp
FileView/FileView.cpp
FileView/FileItem.cpp
FileView/TitleView.cpp
DirMenu/DirMenu.cpp
DirMenu/DirMenuItem.cpp
ColorPicker/ColorPicker.cpp
Walter/Spinner.cpp
../common/stat.cpp
../common/misc.cpp
<<

IComm/IShelf.cpp

XTRAFLAGS=-g
COMPILE=gcc $XTRAFLAGS -c $SRCFILE -o $MODULE.$OBJ_EXT
PPONLY=gcc $XTRAFLAGS -E -c $SRCFILE -o $MODULE.$OBJ_EXT

LPREFIX=gcc -o %EXEFILE%
LSUFFIX=-lbe -ltracker

OUTPUT=../line

<DEFAULT
COMPILE=g++ -g -std=gnu++11 -O2 -c %SRCFILE% -Wno-multichar -Wno-unused-result -Wunused-variable -o %MODULE%.%OBJ_EXT%
LPREFIX=g++
LSUFFIX=-o %OUTPUT% -lkaty -lbapi -lX11 -lutil -lpthread
OBJ_EXT=o
OUTPUT=melody
NO_STATERR=1
#BUILDSTAMP=buildstamp.cpp

>>
ScriptContext.cpp
main.cpp
stubs.cpp
MainWindow.cpp
EditArea.cpp
EditPane.cpp
edit.cpp
edit_files.cpp
edit_keys.cpp
edit_cursor.cpp
edit_mouse.cpp
gesture.cpp
drawline.cpp
selection.cpp
edit_actions.cpp
line.cpp
lexer.cpp
redraw.cpp
#Templates.cpp
#InputBox.cpp
projects.cpp
layout.cpp
PopupPane.cpp
CompilePane.cpp
#CompileList.cpp
SearchResultsPane.cpp
#BuildHelpPane.cpp
FileWatcher.cpp
menu.cpp
toolbar.cpp
LNPanel.cpp
spacer.cpp
cursor.cpp
cmdseq.cpp
searchbase.cpp
FindBox.cpp
FindBar.cpp
ReplaceBar.cpp
InfoBar.cpp
#waitspinner.cpp
DocPoint.cpp
undo.cpp
bmatch.cpp
tabs.cpp
misc.cpp
clipboard.cpp
settings.cpp
colors.cpp
#SubWindow.cpp
#ColoredStringItem.cpp
#MessageView.cpp
#stats.cpp
FunctionList.cpp
AutoSaver.cpp
#testview.cpp
redirect.cpp
CList.cpp
script.cpp
script_draw.cpp
timer.cpp
describe_enums.cpp

filepanel/filepanel.cpp
filepanel/filepane.cpp
filepanel/autocomplete.cpp

ria/scanner.cpp
ria/lexer.cpp
ria/compile.cpp
ria/loadsave.cpp
ria/var.cpp
ria/expr.cpp
ria/table.cpp
ria/label.cpp
ria/function.cpp
ria/program.cpp
ria/xcall.cpp
ria/vm.cpp
ria/packnum.cpp
ria/handle.cpp
<<
buildstamp.cpp
