//hash:1f797e3d
//automatically generated by Makegen

/* located in misc2.cpp */

extern "C" {

//---------------------[referenced from misc.cpp]--------------------//
bool CopyFile(const char *src, const char *dst);
uint timer();
int min(int a, int b);
int max(int a, int b);
void DeleteBefore(BString *string, int x);
void DeleteAfter(BString *string, int x);
void AddSuffixIfMissing(char *str, char ch);
int RTrimWhitespace(char *string, int linelength, bool LeaveBlankLinesAlone);
bool IsShiftDown();
bool IsCtrlDown();
bool IsAltDown();
int TranslateAltKey(int ch);
bool GetDirectoryContents(const char *folder, const char *filter, BList *files, BList *dirs);
bool does_filter_match(const char *filespec, const char *filter);
void OpenFolderInTracker(const char *path);
bool MoveToTrash(const char *orgpath);
void errorblip();
void Unimplemented();
char *strwhat(uint in);
bool TrySetFontFamily(BFont *font, const char *desired_face, const char *desired_style);
void CenterWindow(BWindow *parent, BWindow *child, bool at_bottom=false);

};
