//hash:fb49ca68
//automatically generated by Makegen

/* located in UpdateLine.cpp */

//------------------[referenced from UpdateLine.cpp]-----------------//
int UpdateLine(EditView *ev, BView *view, clLine *line, int y, int line_number);
int UpdateLineBB(EditView *ev, BView *view, clLine *line, int y, int line_number);
void DrawTabLine(BView *view, int x, int y, int TabLineColor);
void DrawMaxWidthGuideline(EditView *ev, BView *view, int y1, int y2);
